//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace N_m3u8DL_CLI_SimpleG.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("N_m3u8DL_CLI_SimpleG.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 仅合并音频轨道 的本地化字符串。
        /// </summary>
        public static string audioOnly {
            get {
                return ResourceManager.GetString("audioOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载全部分片,合并为音轨 的本地化字符串。
        /// </summary>
        public static string audioOnly_Tip {
            get {
                return ResourceManager.GetString("audioOnly_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置m3u8文件的Baseurl 的本地化字符串。
        /// </summary>
        public static string baseUrl_Tip {
            get {
                return ResourceManager.GetString("baseUrl_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用二进制合并 的本地化字符串。
        /// </summary>
        public static string binaryMerge {
            get {
                return ResourceManager.GetString("binaryMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采用二进制直接追加合并文件 的本地化字符串。
        /// </summary>
        public static string binaryMerge_Tip {
            get {
                return ResourceManager.GetString("binaryMerge_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 的本地化字符串。
        /// </summary>
        public static string changeDir {
            get {
                return ResourceManager.GetString("changeDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择存储目录 的本地化字符串。
        /// </summary>
        public static string changeDir_Tip {
            get {
                return ResourceManager.GetString("changeDir_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制(_C) 的本地化字符串。
        /// </summary>
        public static string copy {
            get {
                return ResourceManager.GetString("copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剪切(_T) 的本地化字符串。
        /// </summary>
        public static string cut {
            get {
                return ResourceManager.GetString("cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合并后删除分片 的本地化字符串。
        /// </summary>
        public static string deleteAfterDone {
            get {
                return ResourceManager.GetString("deleteAfterDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 勾选此项后合并完毕将删除所有分片 的本地化字符串。
        /// </summary>
        public static string deleteAfterDone_Tip {
            get {
                return ResourceManager.GetString("deleteAfterDone_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭完整性检查 的本地化字符串。
        /// </summary>
        public static string disableCheck {
            get {
                return ResourceManager.GetString("disableCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载完毕后跳过检查分片数量是否与m3u8内描述的文件数量一致 的本地化字符串。
        /// </summary>
        public static string disableCheck_Tip {
            get {
                return ResourceManager.GetString("disableCheck_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合并时不写入日期 的本地化字符串。
        /// </summary>
        public static string disableDate {
            get {
                return ResourceManager.GetString("disableDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用ffmpeg混流时不写入Date属性 的本地化字符串。
        /// </summary>
        public static string disableDate_Tip {
            get {
                return ResourceManager.GetString("disableDate_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载完成后不合并 的本地化字符串。
        /// </summary>
        public static string disableMerge {
            get {
                return ResourceManager.GetString("disableMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不合并视频分片 的本地化字符串。
        /// </summary>
        public static string disableMerge_Tip {
            get {
                return ResourceManager.GetString("disableMerge_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不使用系统代理 的本地化字符串。
        /// </summary>
        public static string disableProxy {
            get {
                return ResourceManager.GetString("disableProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不主动使用系统代理 的本地化字符串。
        /// </summary>
        public static string disableProxy_Tip {
            get {
                return ResourceManager.GetString("disableProxy_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行程序 的本地化字符串。
        /// </summary>
        public static string exeToRun {
            get {
                return ResourceManager.GetString("exeToRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载器主程序的文件名 的本地化字符串。
        /// </summary>
        public static string exeToRun_Tip {
            get {
                return ResourceManager.GetString("exeToRun_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 混流MP4边下边看 的本地化字符串。
        /// </summary>
        public static string fastStart {
            get {
                return ResourceManager.GetString("fastStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用ffmpeg混流时将元数据移动到头部 的本地化字符串。
        /// </summary>
        public static string fastStart_Tip {
            get {
                return ResourceManager.GetString("fastStart_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取下载器(_N) 的本地化字符串。
        /// </summary>
        public static string getDL {
            get {
                return ResourceManager.GetString("getDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击我即可调用下载器 的本地化字符串。
        /// </summary>
        public static string go_Tip {
            get {
                return ResourceManager.GetString("go_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求头 的本地化字符串。
        /// </summary>
        public static string headers {
            get {
                return ResourceManager.GetString("headers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 为请求添加 HTTP Header 的本地化字符串。
        /// </summary>
        public static string headers_Tip {
            get {
                return ResourceManager.GetString("headers_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义IV 的本地化字符串。
        /// </summary>
        public static string iv {
            get {
                return ResourceManager.GetString("iv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入HEX字符串 的本地化字符串。
        /// </summary>
        public static string iv_Tip {
            get {
                return ResourceManager.GetString("iv_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义KEY 的本地化字符串。
        /// </summary>
        public static string key {
            get {
                return ResourceManager.GetString("key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可拖入16字节的本地KEY文件或输入Base64字符串 的本地化字符串。
        /// </summary>
        public static string key_Tip {
            get {
                return ResourceManager.GetString("key_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 M3U8地址 的本地化字符串。
        /// </summary>
        public static string m3u8 {
            get {
                return ResourceManager.GetString("m3u8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可以输入或拖入文件; 拖入文件夹或txt以批量下载; 双击从剪贴板获取 的本地化字符串。
        /// </summary>
        public static string m3u8_Tip {
            get {
                return ResourceManager.GetString("m3u8_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 限速(kb/s) 的本地化字符串。
        /// </summary>
        public static string maxSpeed {
            get {
                return ResourceManager.GetString("maxSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置下载限速;0为不限制 的本地化字符串。
        /// </summary>
        public static string maxSpeed_Tip {
            get {
                return ResourceManager.GetString("maxSpeed_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大线程 的本地化字符串。
        /// </summary>
        public static string maxThread {
            get {
                return ResourceManager.GetString("maxThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序将尝试使用不高于此数值的线程下载 的本地化字符串。
        /// </summary>
        public static string maxThread_Tip {
            get {
                return ResourceManager.GetString("maxThread_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小线程 的本地化字符串。
        /// </summary>
        public static string minThread {
            get {
                return ResourceManager.GetString("minThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序将尝试使用不低于此数值的线程下载 的本地化字符串。
        /// </summary>
        public static string minThread_Tip {
            get {
                return ResourceManager.GetString("minThread_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 混流文件 的本地化字符串。
        /// </summary>
        public static string muxJson {
            get {
                return ResourceManager.GetString("muxJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可拖入特定的json文件 的本地化字符串。
        /// </summary>
        public static string muxJson_Tip {
            get {
                return ResourceManager.GetString("muxJson_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动参数 的本地化字符串。
        /// </summary>
        public static string parm {
            get {
                return ResourceManager.GetString("parm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本程序生成的启动参数 的本地化字符串。
        /// </summary>
        public static string parm_Tip {
            get {
                return ResourceManager.GetString("parm_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅解析m3u8 的本地化字符串。
        /// </summary>
        public static string parseOnly {
            get {
                return ResourceManager.GetString("parseOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在解析m3u8之后退出程序,仅生成meta.json 的本地化字符串。
        /// </summary>
        public static string parseOnly_Tip {
            get {
                return ResourceManager.GetString("parseOnly_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粘贴(_P) 的本地化字符串。
        /// </summary>
        public static string paste {
            get {
                return ResourceManager.GetString("paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 范围选择 的本地化字符串。
        /// </summary>
        public static string range {
            get {
                return ResourceManager.GetString("range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置开始时间或开始分片序号 的本地化字符串。
        /// </summary>
        public static string range_Tip1 {
            get {
                return ResourceManager.GetString("range_Tip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置终止时间或终止分片序号 的本地化字符串。
        /// </summary>
        public static string range_Tip2 {
            get {
                return ResourceManager.GetString("range_Tip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重试次数 的本地化字符串。
        /// </summary>
        public static string retryCount {
            get {
                return ResourceManager.GetString("retryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 遇到停止速度时,程序尝试重新下载的次数 的本地化字符串。
        /// </summary>
        public static string retryCount_Tip {
            get {
                return ResourceManager.GetString("retryCount_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置代理 的本地化字符串。
        /// </summary>
        public static string setProxy {
            get {
                return ResourceManager.GetString("setProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入http/socks5代理地址，如http://127.0.0.1:8080. 的本地化字符串。
        /// </summary>
        public static string setProxy_Tip {
            get {
                return ResourceManager.GetString("setProxy_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停速(kb/s) 的本地化字符串。
        /// </summary>
        public static string stopSpeed {
            get {
                return ResourceManager.GetString("stopSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当下载速度连续几次低于此数值时,重新下载 的本地化字符串。
        /// </summary>
        public static string stopSpeed_Tip {
            get {
                return ResourceManager.GetString("stopSpeed_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择一个目录，视频将会下载到此处 的本地化字符串。
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到程序 的本地化字符串。
        /// </summary>
        public static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 URL为必填项 的本地化字符串。
        /// </summary>
        public static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请稍候 的本地化字符串。
        /// </summary>
        public static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非预期的byte格式 的本地化字符串。
        /// </summary>
        public static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非16 Bytes文件 的本地化字符串。
        /// </summary>
        public static string String6 {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持该代理链接! 的本地化字符串。
        /// </summary>
        public static string String7 {
            get {
                return ResourceManager.GetString("String7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超时时长(s) 的本地化字符串。
        /// </summary>
        public static string timeout {
            get {
                return ResourceManager.GetString("timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置请求超时时长 的本地化字符串。
        /// </summary>
        public static string timeout_Tip {
            get {
                return ResourceManager.GetString("timeout_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视频标题 的本地化字符串。
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 双击此处可以自动获取视频标题 的本地化字符串。
        /// </summary>
        public static string title_Tip {
            get {
                return ResourceManager.GetString("title_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 置顶窗口 的本地化字符串。
        /// </summary>
        public static string topMost {
            get {
                return ResourceManager.GetString("topMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 置顶当前窗口 的本地化字符串。
        /// </summary>
        public static string topMost_Tip {
            get {
                return ResourceManager.GetString("topMost_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作目录 的本地化字符串。
        /// </summary>
        public static string workDir {
            get {
                return ResourceManager.GetString("workDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存储目录，文件将会被下载到这里 的本地化字符串。
        /// </summary>
        public static string workDir_Tip {
            get {
                return ResourceManager.GetString("workDir_Tip", resourceCulture);
            }
        }
    }
}
